UPDATE: Add super admin

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -46,9 +46,18 @@ services:
       - -c
       - |
         DB_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
-        
-        echo "Running migrations..."
-        /migrate -path /migrations -database "$$DB_URL" up
+
+        for i in 1 2 3; do
+          echo "Migration attempt $$i..."
+          if /migrate -path /migrations -database "$$DB_URL" up; then
+            echo "Migration success"
+            exit 0
+          fi
+          sleep 2
+        done
+
+        echo "Migration failed after 3 attempts"
+        exit 1
     networks:
       - history-api-project
 
